# Generated by Django 5.2.13 on 2026-05-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAndDistanceValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('km_value', models.FloatField()),
                ('min_value', models.FloatField()),
            ],
            options={
                'db_table': 'time_and_distance_values',
            },
        ),
    ]
