# Generated by Django 5.2.13 on 2026-05-25 05:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fare_offered', models.FloatField()),
                ('pickup_description', models.CharField(max_length=255)),
                ('destination_description', models.CharField(max_length=255)),
                ('fare_assigned', models.FloatField(null=True)),
                ('client_rating', models.FloatField(null=True)),
                ('driver_rating', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACCEPTED', 'ACCEPTED'), ('ON_THE_WAY', 'ON_THE_WAY'), ('ARRIVED', 'ARRIVED'), ('TRAVELLING', 'TRAVELLING'), ('FINISHED', 'FINISHED'), ('CANCELLED', 'CANCELLED')], default='CREATED', max_length=20)),
                ('pickup_position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('destination_position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='users.user')),
                ('id_driver_assigned', models.ForeignKey(db_column=' id_driver_assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_requests', to='users.user')),
            ],
            options={
                'db_table': 'client_requests',
            },
        ),
    ]
