# Generated by Django 5.2.13 on 2026-06-06 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='clientrequest',
                    name='id_driver_assigned',
                    field=models.ForeignKey(
                        db_column='id_driver_assigned',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='driver_requests',
                        to='users.user',
                    ),
                ),
            ],
        ),
    ]
