# Generated by Django 5.2.13 on 2026-05-20 22:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPosition',
            fields=[
                ('id_driver', models.OneToOneField(db_column='id_driver', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='drivers_position', serialize=False, to='users.user')),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'drivers_position',
            },
        ),
    ]
