# Generated by Django 5.2.13 on 2026-05-28 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverBikeInfo',
            fields=[
                ('id_driver', models.OneToOneField(db_column='id_driver', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('brand', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('plate', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'driver_bike_info',
            },
        ),
    ]
