# Generated by Django 5.2.13 on 2026-05-26 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_requests', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTripOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fare_offered', models.FloatField()),
                ('time', models.FloatField()),
                ('distance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_client_request', models.ForeignKey(db_column='id_client_request', on_delete=django.db.models.deletion.CASCADE, to='client_requests.clientrequest')),
                ('id_driver', models.ForeignKey(db_column='id_driver', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'driver_trip_offers',
            },
        ),
    ]
